### PR TITLE
[NO_TICKET] Update to CMSDS 2.2.0

### PR DESCRIPTION
**Pull request by bernardwang**
### Summary
- Upgrade to CMSDS 2.2.0
- Fix`<StepList>` definition files

### How to test
- Run and test the doc site with `yarn start`
- Test this HCgov DS version in your HCgov application. I recommend doing this by first building this branch with `yarn build`, and then installing it locally in your application by replacing the `@cmsgov/ds-healthcare-gov` dependency in your application's package.json like so:
```
"@cmsgov/ds-healthcare-gov": "file:../hcgov-design-system",  
```

### CODE REVIEW

**Review by nichia — COMMENTED** [review]
Getting error messages on `windowshop`:
```Starting the development server...

Failed to compile.

/Users/tchutnichia/Code/Support/windowshop/src/components/StepsPage/StepsPage.tsx
TypeScript error in /Users/tchutnichia/Code/Support/windowshop/src/components/StepsPage/StepsPage.tsx(53,19):
Type '{ heading: string; steps: { heading: string; linkText: string; completed: boolean; href: string; }[]; href: string; }' is not assignable to type 'StepProps'.
  Object literal may only specify known properties, and 'heading' does not exist in type 'StepProps'.  TS2322

    51 |               steps={[
    52 |                 {
  > 53 |                   heading: __("step_optional_title"),
       |                   ^
    54 |                   // TODO: Below needs to be address in design system
    55 |                   // @ts-ignore - DS doesn't support type for nested steps
    56 |                   steps: optionalSteps,
```

**Comment by nichia** [comment]
For some reason, I'm still getting the same error message as before.

**Review by nichia — APPROVED** [review]
Great, that works.

**Comment by line47** [comment]
Tested with Windowshop and tested the doc site and both look to be working as expected!

**Review by line47 — APPROVED** [review]

**Pull request merged**
