### PR TITLE
LHDM-72 footer can now be server side rendered

### PR DESCRIPTION
**Pull request by DavidMCarek**

### CODE REVIEW

**Review by nichia — APPROVED** [review]
:rocket:

**Review by LouisFettet — APPROVED** [review]
LGTM; when linking to local versions of both the CMS DS and HCGOV DS, our Gatsby project is now able to render everything with JS disabled. :shipit: 

I did run into an issue where using the current version of the CMS DS (`2.7.1`) produced errors with server-side rendering (possibly due to `classnames`?), but the main branch worked fine.

@line47 it would be great for our team to get a hold of this change soon; do y'all have an ETA on the next release? Ideally it would include a CMS DS upgrade as well as this change.

**Comment by line47** [comment]
Can you say more about this @LouisFettet ? 
> I did run into an issue where using the current version of the CMS DS (2.7.1) produced errors with server-side rendering (possibly due to classnames?), but the main branch worked fine.

**Comment by LouisFettet** [comment]
> Can you say more about this @LouisFettet ?
> 
> > I did run into an issue where using the current version of the CMS DS (2.7.1) produced errors with server-side rendering (possibly due to classnames?), but the main branch worked fine.

@line47 sure! I use `yarn link` when working with the DS so I can reference local changes to the DS in a project. When I locally linked the CMS DS to the HCGOV DS to the project, everything worked fine. But when I only had the HCGOV DS linked to the project (i.e. CMS DS was being pulled in from remote), I ran into a one-off "Element type" error that prevented server-side rendering. I'm not going to sweat it for now, since it could stem from any number of issues. We can investigate further if we run into it again once we're pulling in all dependencies from remotes (no local links).

**Pull request merged**
